### PR TITLE
Vision Transformer for ADNI dataset - Deren Teo (45285545)

### PR DESCRIPTION
**Pull request by deren-teo**
This pull request implements a Vision Transformer for classifying MRI brain images as being either cognitive normal or representative of Alzheimer's disease. A patient-level test accuracy of 75.11% is achieved using transfer learning techniques.

This PR contains the following main files:
- `dataset.py` - data loading and pre-processing
- `modules.py` - ViT implementation
- `predict.py` - run inference on ADNI test split or interactively using a web GUI
- `train.py` - train and save a model to use with `predict.py`

This PR also contains a utility script, `plot_metrics.py`, which can be used to plot the training and validation metrics written by the model after training. More details on all aspects can be found in the `README`.

Best regards,
Deren Teo (45285545)

### CODE REVIEW

**Comment by aryaman-sh** [comment]
**This is an initial inspection, no action required**

**Difficulty**
- Hard
- Task 6

**Readme**
- Excellent 

**Commit messages**
- good

**Code**
- Good structure
- Comments not adequate

**Functionality/Performance**
- 75.11%
- Good

**Comment by deren-teo** [comment]
Not sure if I misunderstood whether or not I'm supposed/allowed to make changes in response to this initial feedback. If not, please ignore the latest commit for marking purposes.

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem 
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe acceptable/good
Model/technical explanation
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Comment by shakes76** [comment]
Need you to remove the gitignore so that PR can be merged. Does not affect grade but enables a merge to main repo

**Comment by deren-teo** [comment]
Apologies, I have removed it now.

**Comment by wangzhaomxy** [comment]
Feedback attempt and no feedback marks lost.

**Pull request merged**
