### PR TITLE
Topic recognition - Vision Transformer for Alzheimer's Classification, s4532823

### PR DESCRIPTION
**Pull request by lockster99**
Name: Lachlan Blaine
Student ID: 45328237

Task 6 - Classify Alzheimer's disease using a visual transformer.

This implementation of a vision transformer was used to classify Alzheimer's disease from brain scans in the Alzheimer's Disease Neuroimaging Initiative (ADNI) dataset.

Further information on model architecture, data loading/preprocessing, training/results, dependencies & reproducibility are available in the README.md file.

### CODE REVIEW

**Comment by LinfengLiu98** [comment]
**This is an initial inspection, no action is required at this point**

Difficulty: Hard

Readme:
Excellent

Commit messages: Excellent, detailed.

Code:
- Uses Vision transformer
- Well commented
- Good model design

Functionality/Performance:
- Val accuracy is 67%
- Did patient-level split
- Preprocssing data correctly
- Performed data augmentation
- Well done

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem 
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe acceptable/good
Model/technical explanation could be better -0.5
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description OK, could be better -0.5

**Comment by shakes76** [comment]
Need to remove gitignore file in parent directory causes conflict. Does not affect grade only merge.

**Comment by wangzhaomxy** [comment]
Feedback attempt and no feedback marks lost.

**Pull request merged**
