### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by Cipher0x0**
Report for Segmentation of the Prostate 3D dataset with the UNet3D

### CODE REVIEW

**Comment by WeiDaiwow** [comment]
# Document

- Title: 
	Good
- Address problem:
	Good
- Working Principle:
	More description of UNET3D would be better
- Figure visualization:
	Good
- dependency:
	Good
- inputs and outputs description:
	No input description provided.
	Good output description with visualization and multi-class DSC score table
- training plot:
	Good
- readme using markdown:
	Good
- preprocessing description:
	Not provided
- dataset split description
	Good
- Description of files usage:	
	Not provided


# Check the files:
- modules.py
	Good
- dataset.py
	Good
- train.py
	Good
- predict.py
	Good
	


# Overall:

- solve the problem:
	Yes
- TF/torch implementation:
	Yes
- Design quality:
	Good
- code comments:
	Good
- Difficulty: 
	Unet3D -Normal

**Comment by Cipher0x0** [comment]
> # Document
> * Title:
>   Good
> * Address problem:
>   Good
> * Working Principle:
>   More description of UNET3D would be better
> * Figure visualization:
>   Good
> * dependency:
>   Good
> * inputs and outputs description:
>   No input description provided.
>   Good output description with visualization and multi-class DSC score table
> * training plot:
>   Good
> * readme using markdown:
>   Good
> * preprocessing description:
>   Not provided
> * dataset split description
>   Good
> * Description of files usage:
>   Not provided
> 
> # Check the files:
> * modules.py
>   Good
> * dataset.py
>   Good
> * train.py
>   Good
> * predict.py
>   Good
> 
> # Overall:
> * solve the problem:
>   Yes
> * TF/torch implementation:
>   Yes
> * Design quality:
>   Good
> * code comments:
>   Good
> * Difficulty:
>   Unet3D -Normal

Feedback have received, deficiencies will be improved within a few days.

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem 
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting
No Data leakage
Difficulty: Normal -5
## Commit Log
Meaningful commit messages sometimes -1
Progressive commits used
## Documentation
ReadMe acceptable/good
Model/technical explanation
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description minimal -1

**Comment by shakes76** [comment]
Could not idenitfy you from your account, can you add student ID or equivalent so I can enter marks?

**Comment by Cipher0x0** [comment]
I'm sorry for causing that, I will add my student ID to both this email and Readme in github
46949750
________________________________
发件人: Shakes ***@***.***>
发送时间: 2023年11月16日 21:21
收件人: shakes76/PatternAnalysis-2023 ***@***.***>
抄送: Cipher ***@***.***>; Author ***@***.***>
主题: Re: [shakes76/PatternAnalysis-2023] Topic recognition (PR #34)


Could not idenitfy you from your account, can you add student ID or equivalent so I can enter marks?

―

**Comment by wangzhaomxy** [comment]
Feedback attempt and no feedback marks lost. Marks have been added.

**Pull request merged**
