### PR TITLE
Improved UNET Segmentation Task on the ISIC 2018 Dataset 

### PR DESCRIPTION
**Pull request by lombo9**
This is the initial pull request. Includes a README file and the model.py, train.py, dataset.py and predict.py scripts. More information can be found in the README file, that explains the improved UNET algorithm, and the scripts used to run it. It also includes some results from the algorithm.

Thank you,
Thomas Witherspoon s45857139

### CODE REVIEW

**Comment by wangzhaomxy** [comment]
This is an initial inspection, no action is required at this point.

- Wrong files path. All student constructed document should be packed in the ‘recognition’ document.
- Try to use PyTorch to construct the Improved U-Net model, but the model body is roughly a classical U-Net model instead of the improved U-Net one. No data augmentation.
- There is no training code in train.py, just some support functions for model training.
- The code in predict.py is not for predicting output by using well trained model but for training the model in just one epoch. As per the code in this file, it cannot output nether the multiple epochs training graph nor musks.
- Sufficient docstring and comment in the code, but need some references.
- Wrong pull request branch, from local:topic-recognition to shakes76:main

**Comment by lombo9** [comment]
Thank you for the feedback!

I have modified my UNET algorithm to make sure that it replicates the improved UNET algorithm. These changes are found in the new modules.py. I have also made sure that all content I created is kept outside of the recognition folder. I also made modifications to train.py so that it doesn't just have training functions, but actually uses them in main.  I have also changed the base branch from main to topic-recognition

I have some more modifications to make, such as:
-  Adding documentation to the new ImprovedUNET model,
-  Reconfiguring the README document to reflect these changes
- Modifying the predict.py file to make sure it does its intended purpose

**Comment by lombo9** [comment]
I have now made all of my changes. In summary, I created a new modules.py, this time containing the improved UNET, instead of a classical UNET. Also edited predict.py script to actually test an output of the saved trained model. Also edited the train.py to not just contain the training functions, but to actually use them and train the model. I also fixed the file path and PR branch location, and added references to the README. I also made it so the default epochs is 75 (what I used to train my model).

Thank you!
Have a nice Christmas

**Comment by shakes76** [comment]
# Marking
Changes made after the due date have been ignored to fairness to other students who have achieved their work in time.
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation, not Improved UNet but UNet -4
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem, but no code for multiple epochs -2
Driver Script present, no predict code -2
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting
No Data leakage
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe acceptable, minimal usage -1
Model/technical explanation not done -1
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in InCorrect Branch) -2 (from initial PR)
No Feedback required as fixed branch issues -2 +2
Request Description minimal -1

**Comment by shakes76** [comment]
Merge done because post deadline updates makes model usage and useful.

**Pull request merged**
