### PR TITLE
Siamese network classifier on the ADNI brain data-S46994554-Qianchen Zhao

### PR DESCRIPTION
**Pull request by SKY-YY88**
Task 7 - Create a Siamese network classifier to classify Alzheimer's disease (normal and AD) in the ADNI brain dataset with an accuracy of 0.91 on the test set.

The files are broken down as follows:

train.py： Training file, called by run_train.sh.

predict_begin.py： Inference startup file, reads data, initializes the network, and outputs the similarity of two pictures.

predict.py： Inference files, data preprocessing, model inference, result comparison.

nets/modules.py： Siamese network results, after using the backbone of vgg16 to extract features,
Use the feature values of the two images as the L1 distance and output the predicted value.

nets/vgg.py：vgg16 basic network, used to extract features.

utils/dataset.py： Read the data set, prepare the input data into pairs, read the image, crop, normalize and send it to the network.

utils/utils_aug.py： Data augmentation (not used yet)

utils/utils_fit.py： Called by train.py, it traverses the batch data and performs forward propagation and directional propagation.

utils/utils.py： Other related tools

If you have any questions please let me know

### CODE REVIEW

**Comment by nathasha-naranpanawa** [comment]
**This is an initial inspection, no action is required at this point**

Difficulty: Hard

Readme: Poor
- has some information on algorithm, usage
- results and outputs provided are minimal
- some plots/figures have been provided without any context or discussion

Commit messages: Very poor

Code: 
- design is ok, but file structure is unnecessarily messy, looks like a lot of them are just copy-pasted code
- zero comments
- **only a siamese network has been implemented, no classifier**

Functionality/Performance: 
- **only performing similarity detection between pairs of images, no classification**
- I'm assuming the 'accuracy - 0.91' is for the siamese but not sure if it's for the test set
- no other performance numbers have been provided

General comments:
- **algorithm solves the respective problem only half-way**
- you need to have added a classifier that can classify an individual image as AD or NC with their features extracted by the trained triplet network

**Comment by SKY-YY88** [comment]
Can we modify the code and Readme according to the feedback? 

Will the score change after modifying?

Thank you!

**Comment by SKY-YY88** [comment]
> **This is an initial inspection, no action is required at this point**
> 
> Difficulty: Hard
> 
> Readme: Poor
> 
> * has some information on algorithm, usage
> * results and outputs provided are minimal
> * some plots/figures have been provided without any context or discussion
> 
> Commit messages: Very poor
> 
> Code:
> 
> * design is ok, but file structure is unnecessarily messy, looks like a lot of them are just copy-pasted code
> * zero comments
> * **only a siamese network has been implemented, no classifier**
> 
> Functionality/Performance:
> 
> * **only performing similarity detection between pairs of images, no classification**
> * I'm assuming the 'accuracy - 0.91' is for the siamese but not sure if it's for the test set
> * no other performance numbers have been provided
> 
> General comments:
> 
> * **algorithm solves the respective problem only half-way**
> * you need to have added a classifier that can classify an individual image as AD or NC with their features extracted by the trained triplet network

Can we modify the code and Readme according to the feedback? 

Will the score change after modifying?

Thank you!

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem partially no classifier -2
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting minimal -1
No Data leakage
Difficulty: Normal -5
## Commit Log
Meaningful commit messages sometimes -1
Progressive commits used
## Documentation
ReadMe acceptable, missing some info -1
Model/technical explanation
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Comment by SKY-YY88** [comment]
> Difficulty: Normal

why Difficulty is Normal?

**Pull request merged**
