### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by milesgardiner**
This pull request is to merge my attempted solution for recognition problem 7 - classifying the ADNI brain data set with a Siamese classifier, as part of the Report assessment for the COMP3710 course at UQ.

This library implements two networks - a (triplet) Siamese network and a Binary Classifier. The Siamese network is configured to take image tensors and learn a new 'embedded' space to group by class (Alzheimer's disease and normal cognition). The Classifier is designed to take the embeddings from the trained Siamese network as input, and classify the images into the aforementioned classes.

More detail on the networks, and how to use the library is provided in the README.
Included in this library is:
- data preprocessing
- network implementation, training and testing
- script for example usage

Note about commits: 
- you may notice a large number of commits - this is a result of using git to move files to Rangpur. Many commits do not have detailed messages, but this because they are often very small changes. I have provided more detailed messages where significant changes have been made to the code.

### CODE REVIEW

**Comment by nathasha-naranpanawa** [comment]
**This is an initial inspection, no action is required at this point**

Difficulty: Hard

Readme: Poor
- some information is presented on the algorithm and data preprocessing
- **embedded images are not being loaded as they are not in the repo**
- no discussion on results

Commit messages: OK

Code: 
- design is OK
- well commented

Functionality/Performance: 
- **cannot be checked as figures are not shown on the readme and no numbers have been provided separately**

General comments:
- seem to have implemented the algorithm correctly with a triplet network followed by a classifier, with unknown performance

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation, can't verify model without results -3
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem, no performance, can't verify -3
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage, no outputs broken links -2
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages sometimes -1
Progressive commits used
## Documentation
ReadMe acceptable, no usage, no refs -2
Model/technical explanation, no architecture -1
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Comment by shakes76** [comment]
Please remove gitignore file to allow merge. doesnot affect grade only the merge.

**Comment by wangzhaomxy** [comment]
No feedback attempt and no feedback marks lost.

**Comment by wangzhaomxy** [comment]
Feedback attempt and no feedback marks lost.

**Pull request merged**
