### PR TITLE
45711110: OASIS Brain data using StyleGAN2

### PR DESCRIPTION
**Pull request by 4vir4l**
The pull request was updated with README.MD, Images, v2 (single channel GAN) and an improved and commented code for the original source code (StyleGAN2-OASIS).

### CODE REVIEW

**Comment by WeiDaiwow** [comment]
# Document

- Title: 
	Title could be more meaningful.
- Address problem:
	Good
- Working Principle:
	1.Modulated convolution not mentioned in model description
	2. Repeated paragraph for Latent Space in model architecture section
- Figure visualization
	1. all figures' links are broken. Please fix.
- dependency
	not mentioned
- inputs and outputs description:
	1. all figures' links are broken. Please fix.
	2. no visualization of inputs are provided
- training plot:
	 all figures' links are broken. Please fix.
- readme using markdown:
	Good
- preprocessing description:
	Not mentioned
- Description of usage:
	Good



# Check the files:
- modules.py
	Good
- dataset.py
	Good
- train.py		
	No model saving procedure.
- predict.py
	only include function for printing training losses. No usage of trained model and no visualization during inference

	


# Overall:

- solve the problem:
	Not sure. No images shown.
- TF/torch implementation:
	Yes
- Design quality:
	Not sure yet
- code comments:
	Good
- Difficulty: 
	StyleGANv2 -hard



# Pull request

- Please remove the extra files and folders you created outside the StyleGAN2-OASIS_45711110 folder

**Comment by 4vir4l** [comment]
Feedback has been incorporated.

Additionally, following changes were made -  
1. the source code has been adapted to support single channel as well as 3 channel input images.
2. utils.py is created from functions in train.py for cleaner code.
3. Minor changes in model quality to improve generated images.

**Comment by shakes76** [comment]
# Marking
Marked as per the extended due date and changes after which aren't necessarily allowed to contribute to grade for fairness
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation, no prediction code -2
Good spacing and comments
Header blocks
## Recognition Problem 
Maybe Solves problem , no output no results, no plots -4
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage minimal -2
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe minimal on 27th, no refs -1, no usage -1, broken links -1
Model/technical explanation minimal -1
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required, already done -2 +2
Request Description minimal -1

**Comment by shakes76** [comment]
Please revert changes to repo README files for merging, does not affect grade only merge.

**Comment by wangzhaomxy** [comment]
Feedback attempt and feedback marks granted +2. Already done, no more marks added from me. Just a double-check.

**Pull request merged**
