### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by prprakash02**
Hi Team,

This pull request deals with the classification of Alzheimer’s disease of the ADNI brain data 2D (task 6), I tried to incorporate the README.md in the form of a mini-research paper.

This model achieves a testing accuracy close to 92.5% after training for about 27 hours using a100 in rangpur, I have attached all the necessary information in README.md

Thank you so much,

Best Regards,
Prakash

### CODE REVIEW

**Comment by aryaman-sh** [comment]
**This is an initial inspection**

**Difficulty**
- Hard
- Task 6

**Readme**
- Readme in incorrect location
- readme good

**Commit messages**
- good

**Code**
- good structure
- Unexplained commented code in utils.py
- Adequate comments

**Functionality**
- 92.5% accuracy
- Possible data leakage

**Required actions**
- Change README directory

**Comment by prprakash02** [comment]
Hi Aryaman,
Thank you so much for your review.

1. README.md: I have changed the README.md location
2. util.py: All the commented code in util.py is preceded with a block of comment, briefing the purpose of the code (example: "The below commented code block calculates the confusion matrix and the necessary classification details") it may have been slightly hard to see because of the commenting, also the reason to comment was few of those functions are one-time operation such as splitting the data into patient level.
3. Data Leakage: I consulted with Linfeng and Shakes for possible data leakage, please refer util.py (line 723), I compared the files and checked if there is any possible data leakage and found none (I also tried an image wise similarity by checking each image tensor); also if there was a potential leakage the accuracy could be close to 96%

Thank you so much again,

Kind Regards,
Prakash

**Comment by shakes76** [comment]
# Marking
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate design and implementation
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem 
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe good
Model/technical explanation
Good Description and Comments 
Markdown used and PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Comment by shakes76** [comment]
Please revert changes to the repo README and I can merge. Does not affect grade only the merging of PR.

**Comment by prprakash02** [comment]
Hi Shakes,
Thank you so much for your review.

I have restored the original version of README.md

Cheers

**Comment by wangzhaomxy** [comment]
Feedback attempt and no feedback marks lost.

**Pull request merged**
